# Generated by Django 4.2.6 on 2023-11-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_stackoverflow', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_entry',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(max_length=30),
        ),
    ]
