# Generated by Django 4.2.6 on 2023-11-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_stackoverflow', '0003_remove_profile_date_entry_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='author_Id',
            new_name='author_id',
        ),
    ]
