# Generated by Django 4.2.6 on 2023-11-06 08:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('database_stackoverflow', '0005_answer_rating'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('this_tag', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', to='database_stackoverflow.tag'),
        ),
    ]
