# Generated by Django 4.2.6 on 2023-11-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_stackoverflow', '0006_alter_tag_managers_alter_question_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
    ]
