# Generated by Django 4.2.6 on 2023-11-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_stackoverflow', '0007_rename_author_id_answer_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
