# Generated by Django 4.2.6 on 2023-12-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_stackoverflow', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default='acc.png', null=True, upload_to='avatar/%Y/%m/%d'),
        ),
    ]
