# Generated by Django 4.2.6 on 2023-12-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_stackoverflow', '0010_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='database_stackoverflow.profile'),
        ),
    ]
