# Generated by Django 4.2.6 on 2023-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_stackoverflow', '0011_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='acc.png', null=True, upload_to='avatar/%Y/%m/%d'),
        ),
    ]
