# Generated by Django 4.2.6 on 2023-12-10 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_stackoverflow', '0013_questionlikes_answerlikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friends',
            new_name='follows',
        ),
        migrations.AlterField(
            model_name='questionlikes',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_stackoverflow.question'),
        ),
    ]
