# Generated by Django 4.2.6 on 2023-12-12 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_stackoverflow', '0014_rename_friends_profile_follows_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
    ]
