# Generated by Django 4.2.6 on 2023-12-18 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0002_alter_answer_date_alter_answer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 9, 6, 28, 628934, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 9, 6, 28, 628401, tzinfo=datetime.timezone.utc)),
        ),
    ]
